#! /usr/bin/env atf-sh

atf_test_case multi_word
multi_word_body() {
	atf_check \
		-s 'exit:0' \
		-o 'inline:[LEVEL] multi word message\n' \
		/usr/bin/zsh $(atf_get_srcdir)/../lib/aalt-log LEVEL multi word message
}

atf_init_test_cases() {
	atf_add_test_case multi_word
}
